eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:35001/eureka/
logging:
    level:
        net:
            biancheng:
                feign_demo:
                    remote:
                        UserRemoteClient: DEBUG
server:
    port: 35003
swagger:
    authorization:
        key-name: Authorization
