eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:35001/eureka/
    instance:
        instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
        preferIpAddress: true
server:
    port: 35002
spring:
    application:
        name: client-service
